name: End to End Testing with Cypress
on: 
  - pull_request
  - workflow_dispatch

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Environment variables
        run: echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json

      - name: run cypress tests with electron
        uses: cypress-io/github-action@v4
        with:
          browser: electron
